feat: add baidu map plugin
alibaba/spring-ai-alibaba pull request #219
Opened 2024-12-19 00:46 UTC by CoderSerio

### Describe what this PR does / why we need it

Baidu Map is also one of the commonly used apps in daily life, so it is necessary to provide some support for it.

### Does this pull request fix one issue?

#98

### Describe how you did it

With Baidu Map Open APIs

### Describe how to verify it

Originally, there was an example here, but I noticed that this part of the file has been moved to [another repository](https://github.com/springaialibaba/spring-ai-alibaba-examples). I will also add it to the new one as soon as possible

![image](https://github.com/user-attachments/assets/37011107-b4d8-4e10-8a88-d6777cf0cb35)

The part of original example:
```java
@GetMapping("/baiduMap-get-address-weather")
public String baiDuMapGetAddressWeatherFunction(String input) {
    return chatClient.prompt()
        .functions("baiDuMapGetAddressWeatherFunction")
        .system("如果用户输入的内容中想询问天气情况,而且还给定了地址,则使用工具获取天气情况,不然提示用户缺少信息")
        .user(input)
        .call()
        .content();
}
```

### Special notes for reviews

2024-12-19 09:53 UTC, PolarishT commented
Hi, this issue should related to #98

2024-12-19 10:32 UTC, CoderSerio commented
> Hi, this issue should related to #98 

Thx noticing me, and I've added it😘

2024-12-22 14:38 UTC, CoderSerio commented
@PolarishT 
I've implemented the feature to get detailed information about facilities around a specific address. 
And I've retained the ability to retrieve weather information, so both features can be used together.

<img width="1245" alt="image" src="https://github.com/user-attachments/assets/74fc43a2-a3bc-47cc-86c9-c5e8eea7c102" />

Additionally, I've moved the dirs and files into `function-calling` from the original `plugins`

2024-12-24 02:07 UTC, yuluo-yx commented on community/function-calling/spring-ai-alibaba-starter-function-calling-baidumap/pom.xml
> +        <dependency>
用一个序列化框架就可以了，fastjson 可以去掉 都用 jackson

2024-12-24 02:36 UTC, CoderSerio commented on community/function-calling/spring-ai-alibaba-starter-function-calling-baidumap/pom.xml
> +        <dependency>
好的，今天晚上的时候我回去把这一段改掉

2024-12-24 04:32 UTC, PolarishT requested changes

2024-12-24 04:32 UTC, PolarishT commented on community/function-calling/spring-ai-alibaba-starter-function-calling-baidumap/pom.xml
> +        <dependency>
都是用jackson吗？那估计有些functionCalling Impl 得从 gson 转移到 jackjson了

2024-12-24 04:32 UTC, PolarishT commented on community/function-calling/spring-ai-alibaba-starter-function-calling-baidumap/src/main/java/com/alibaba/cloud/ai/functioncalling/baidumap/BaiDuMapConfiguration.java
> +public class BaiDuMapConfiguration {
命名不规范？这里按照规范应该是BaiDuMapAutoConfiguration

2024-12-24 04:36 UTC, yuluo-yx commented
看插件怎么定义了，我看用了 fastjson 所以顺带说了一下


On Tue, Dec 24, 2024 at 12:32 Polarish ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In community/plugins/spring-ai-alibaba-starter-plugin-baidumap/pom.xml
> <https://github.com/alibaba/spring-ai-alibaba/pull/219#discussion_r1891528081>
> :
>
> > +        <dependency>
> +            <groupId>org.springframework.boot</groupId>
> +            <artifactId>spring-boot-configuration-processor</artifactId>
> +            <optional>true</optional>
> +        </dependency>
> +
> +        <dependency>
> +            <groupId>com.alibaba</groupId>
> +            <artifactId>fastjson</artifactId>
> +            <version>1.2.83</version>
> +        </dependency>
> +
> +    </dependencies>
> +
> +    <build>
> +        <finalName>spring-ai-alibaba-plugin-baidumap</finalName>
>
> please update pom.xml we renamed plugin nodule to functionCalling module
> for example, it should be *spring-ai-alibaba-function-calling-baidumap*
> ------------------------------
>
> In
> community/plugins/spring-ai-alibaba-starter-plugin-baidumap/src/main/java/com/alibaba/cloud/ai/plugin/baidumap/BaiDuMapConfiguration.java
> <https://github.com/alibaba/spring-ai-alibaba/pull/219#discussion_r1891598553>
> :
>
> > +import org.springframework.context.annotation.Bean;
> +import org.springframework.context.annotation.Configuration;
> +import org.springframework.context.annotation.Description;
> +
> +/**
> + * @author Carbon
> + */
> ***@***.***
> ***@***.***(BaiDuMapProperties.class)
> ***@***.***(prefix = "spring.ai.alibaba.plugin.baidumap", name = "enabled", havingValue = "true")
> +public class BaiDuMapConfiguration {
> +
> +	@Bean
> +	@ConditionalOnMissingBean
> +	@Description("Get weather information according to address.")
> +	public WeatherSearchService baiDuMapGetAddressWeatherFunction(BaiDuMapProperties baiDuMapProperties) {
>
> bean should end with Function. Forexample, microsoftTranslateFuntion
> ------------------------------
>
> In
> community/plugins/spring-ai-alibaba-starter-plugin-baidumap/src/main/java/com/alibaba/cloud/ai/plugin/baidumap/BaiDuMapProperties.java
> <https://github.com/alibaba/spring-ai-alibaba/pull/219#discussion_r1891602051>
> :
>
> > + *
> + * Unless required by applicable law or agreed to in writing, software
> + * distributed under the License is distributed on an "AS IS" BASIS,
> + * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
> + * See the License for the specific language governing permissions and
> + * limitations under the License.
> + */
> +
> +package com.alibaba.cloud.ai.plugin.baidumap;
> +
> +import org.springframework.boot.context.properties.ConfigurationProperties;
> +
> +/**
> + * @author Carbon
> + */
> ***@***.***(prefix = "spring.ai.alibaba.plugin.baidumap")
>
> it should be spring.ai.alibaba.functioncalling.baidumap
> ------------------------------
>
> In
> community/function-calling/spring-ai-alibaba-starter-function-calling-baidumap/src/main/java/com/alibaba/cloud/ai/functioncalling/baidumap/BaiDuMapConfiguration.java
> <https://github.com/alibaba/spring-ai-alibaba/pull/219#discussion_r1896367790>
> :
>
> > +import org.springframework.boot.autoconfigure.condition.ConditionalOnClass;
> +import org.springframework.boot.autoconfigure.condition.ConditionalOnMissingBean;
> +import org.springframework.boot.autoconfigure.condition.ConditionalOnProperty;
> +import org.springframework.boot.context.properties.EnableConfigurationProperties;
> +import org.springframework.context.annotation.Bean;
> +import org.springframework.context.annotation.Configuration;
> +import org.springframework.context.annotation.Description;
> +
> +/**
> + * @author Carbon
> + */
> ***@***.***
> ***@***.***(MapSearchService.class)
> ***@***.***(BaiDuMapProperties.class)
> ***@***.***(prefix = "spring.ai.alibaba.functioncalling.baidumap", name = "enabled", havingValue = "true")
> +public class BaiDuMapConfiguration {
>
> 命名不规范？这里按照规范应该是BaiDuMapAutoConfiguration
> ------------------------------
>
> In
> community/plugins/spring-ai-alibaba-starter-plugin-baidumap/src/main/java/com/alibaba/cloud/ai/plugin/baidumap/BaiDuMapConfiguration.java
> <https://github.com/alibaba/spring-ai-alibaba/pull/219#discussion_r1891604798>
> :
>
> > +import org.springframework.context.annotation.Bean;
> +import org.springframework.context.annotation.Configuration;
> +import org.springframework.context.annotation.Description;
> +
> +/**
> + * @author Carbon
> + */
> ***@***.***
> ***@***.***(BaiDuMapProperties.class)
> ***@***.***(prefix = "spring.ai.alibaba.plugin.baidumap", name = "enabled", havingValue = "true")
> +public class BaiDuMapConfiguration {
> +
> +	@Bean
> +	@ConditionalOnMissingBean
> +	@Description("Get weather information according to address.")
> +	public WeatherSearchService baiDuMapGetAddressWeatherFunction(BaiDuMapProperties baiDuMapProperties) {
>
> the class should named as XxxAutoConfiguration
> ------------------------------
>
> In
> community/function-calling/spring-ai-alibaba-starter-function-calling-baidumap/pom.xml
> <https://github.com/alibaba/spring-ai-alibaba/pull/219#discussion_r1896366524>
> :
>
> > +            <groupId>com.fasterxml.jackson.core</groupId>
> +            <artifactId>jackson-annotations</artifactId>
> +        </dependency>
> +
> +        <dependency>
> +            <groupId>org.springframework.ai</groupId>
> +            <artifactId>spring-ai-spring-boot-autoconfigure</artifactId>
> +        </dependency>
> +
> +        <dependency>
> +            <groupId>org.springframework.boot</groupId>
> +            <artifactId>spring-boot-configuration-processor</artifactId>
> +            <optional>true</optional>
> +        </dependency>
> +
> +        <dependency>
>
> 都是用jackson吗？那估计有些functionCalling Impl 得从 gson 转移到 jackjson了
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/alibaba/spring-ai-alibaba/pull/219#pullrequestreview-2513935744>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ASS2GCPMEY5CAKIKJE6C36D2HDPVXAVCNFSM6AAAAABT326IQ6VHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDKMJTHEZTKNZUGQ>
> .
> You are receiving this because you commented.Message ID:
> ***@***.***>
>

2024-12-24 13:07 UTC, PolarishT commented
统一使用JackSon吧～ 我们和Spring的生态对齐

2024-12-24 15:00 UTC, CoderSerio commented
> 统一使用JackSon吧～ 我们和Spring的生态对齐

> 看插件怎么定义了，我看用了 fastjson 所以顺带说了一下

稍后我去改一下，辛苦二位的CR!

2024-12-24 17:46 UTC, CoderSerio commented
Done. 辛苦大佬们有空再帮忙 CR 看下有没有什么问题。

2024-12-25 05:33 UTC, PolarishT approved these changes
LGTM

2024-12-25 06:05 UTC, merged