feat: add news plugin
alibaba/spring-ai-alibaba pull request #226
Opened 2024-12-19 06:50 UTC by xiaohai-78

### Describe what this PR does / why we need it

### Does this pull request fix one issue?

### Describe how you did it

### Describe how to verify it

### Special notes for reviews

2024-12-19 06:51 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/alibaba/spring-ai-alibaba?pullRequest=226) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/alibaba/spring-ai-alibaba?pullRequest=226) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: xiaohai-78<br/>:x: xiaoyuntao<br/><hr/>**xiaoyuntao** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/alibaba/spring-ai-alibaba?pullRequest=226) it.</sub>

2024-12-19 09:50 UTC, PolarishT reviewed
for building more atom modules, we encourage contributors to separate news functionCalling module into two modules.
for example, **spring ai alibaba sina module** and **spring ai alibaba toutiao module**

2024-12-19 09:50 UTC, PolarishT commented on community/plugins/spring-ai-alibaba-starter-plugin-news/pom.xml
> +		</dependency>
please add space for each dependency

2024-12-19 09:50 UTC, PolarishT commented on community/plugins/spring-ai-alibaba-starter-plugin-news/pom.xml
> +				<groupId>org.springframework.boot</groupId>
please add fileName and remove other plugins irrelevant

2024-12-19 09:50 UTC, PolarishT commented on community/plugins/spring-ai-alibaba-starter-plugin-news/src/main/java/com/alibaba/cloud/ai/plugin/news/NewsAutoConfiguration.java
> +@ConditionalOnClass({ SinaService.class, ToutiaoService.class })
add ConditionalonProperty annotation in order to implement free loading

2024-12-19 09:50 UTC, PolarishT commented on community/plugins/spring-ai-alibaba-starter-plugin-news/src/main/java/com/alibaba/cloud/ai/plugin/news/NewsAutoConfiguration.java
> +	@Description("Get the news from the toutiao news (获取今日头条新闻).")
each bean should end with Function

2024-12-19 09:50 UTC, PolarishT commented on community/plugins/spring-ai-alibaba-starter-plugin-news/src/main/java/com/alibaba/cloud/ai/plugin/news/NewsService.java
> +public abstract class NewsService<T extends NewsService.Request, R extends NewsService.Response>
it should use XxxNewsService better, and does not use genericity

2024-12-19 09:50 UTC, PolarishT commented on spring-ai-alibaba-examples/function-calling-example/pom.xml
> +			<artifactId>spring-ai-alibaba-starter-plugin-news</artifactId>
we changed plugin module into functioncalling module

```
<dependency>
<groupId>com.alibaba.cloud.ai</groupId>
<artifactId>spring-ai-alibaba-starter-function-calling-news</artifactId>
<dependency>
```

2024-12-23 02:04 UTC, xiaohai-78 commented
done

2024-12-23 09:03 UTC, PolarishT requested changes

2024-12-23 09:03 UTC, PolarishT commented on pom.xml
> +        <module>community/plugins/spring-ai-alibaba-starter-function-calling-toutiaonews</module>
这里怎么是 plugins ？应该是 funcationCalling 吧～ 是不是忘记更新代码啦～

2024-12-24 02:06 UTC, yuluo-yx commented on spring-ai-alibaba-examples/function-calling-example/pom.xml
> +		<dependency>
example module 已经移除了，这部分可以删掉，然后在 exmaple 仓库提交一下？

2024-12-24 02:26 UTC, xiaohai-78 commented on spring-ai-alibaba-examples/function-calling-example/pom.xml
> +		<dependency>
ok

2024-12-24 02:27 UTC, closed without merging