feat: add baidu translation impl
alibaba/spring-ai-alibaba pull request #298
Opened 2024-12-21 07:43 UTC by SCMRCORE

### Describe what this PR does / why we need it
The implementation of the Baidu translation component

### Does this pull request fix one issue?

#98 

### Describe how you did it
With Baidu translation Open APIs

### Describe how to verify it
I implemented a text translation and here are two examples:
success
<img width="874" alt="文本翻译成功" src="https://github.com/user-attachments/assets/749ef9cf-10a9-4ad2-926a-0af6623ce4cd" />
failure
<img width="912" alt="文本翻译异常情况" src="https://github.com/user-attachments/assets/2ea65812-2dff-439f-a00d-8c43c31b185b" />

### Special notes for reviews

2024-12-21 07:43 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/alibaba/spring-ai-alibaba?pullRequest=298) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/alibaba/spring-ai-alibaba?pullRequest=298) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/alibaba/spring-ai-alibaba?pullRequest=298) it.</sub>

2024-12-21 13:15 UTC, PolarishT commented on community/function-calling/spring-ai-alibaba-starter-function-calling-baidutranslate/src/main/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports
please add space

2024-12-21 13:23 UTC, PolarishT requested changes
please use maven profile: license env to build license header

2024-12-22 14:38 UTC, SCMRCORE commented
> 请使用 maven 配置文件：许可证环境构建许可证标头

Thanks, I changed the other problems first, and when you merge your pr, I can use the plugin to change the license. QAQ

2024-12-24 02:02 UTC, yuluo-yx commented on community/function-calling/spring-ai-alibaba-starter-function-calling-baidutranslate/src/main/java/com/alibaba/cloud/ai/functioncalling/baidutranslate/BaidutranslateService.java
> +		if (jsonElement.getAsJsonObject().has("error_code")) {
这个判断是不是不太严谨？没有 code 之类的吗？

2024-12-24 02:02 UTC, yuluo-yx commented on community/function-calling/spring-ai-alibaba-starter-function-calling-baidutranslate/src/main/java/com/alibaba/cloud/ai/functioncalling/baidutranslate/TranslationResponse.java
> +class TranslationResponse {
Request 都用了 record 这里是不是可以和 request 一起使用 record type 定义？

2024-12-24 02:02 UTC, yuluo-yx commented on community/function-calling/spring-ai-alibaba-starter-function-calling-baidutranslate/src/main/java/com/alibaba/cloud/ai/functioncalling/baidutranslate/TranslationResult.java
> +class TranslationResult {
ditto

2024-12-24 02:50 UTC, SCMRCORE commented on community/function-calling/spring-ai-alibaba-starter-function-calling-baidutranslate/src/main/java/com/alibaba/cloud/ai/functioncalling/baidutranslate/BaidutranslateService.java
> +		Gson gson = new Gson();
Sorry, before developing this pluging, I studied the TranslateService.java and used this

2024-12-24 02:59 UTC, SCMRCORE commented on community/function-calling/spring-ai-alibaba-starter-function-calling-baidutranslate/src/main/java/com/alibaba/cloud/ai/functioncalling/baidutranslate/BaidutranslateService.java
> +		if (jsonElement.getAsJsonObject().has("error_code")) {
I originally wanted to use one class/record to map this response, but Baidu Translate API gave the response  belike:
<img width="527" alt="百度翻译响应" src="https://github.com/user-attachments/assets/ce1af24d-ed99-4f99-be4e-5ab6eef555f8" />
so, I use " if " and return the error_code and error_msg. 
And If there's a better way , I will correct this part  ,please tell me thanks. QAQ

2024-12-24 03:24 UTC, yuluo-yx commented on community/function-calling/spring-ai-alibaba-starter-function-calling-baidutranslate/src/main/java/com/alibaba/cloud/ai/functioncalling/baidutranslate/BaidutranslateService.java
> +		if (jsonElement.getAsJsonObject().has("error_code")) {
imo, 可以先拿到 errcode 的值，然后和错误码比较一下，不是判断是不是有这个字段存在

可以先判断此次 http 请求是否成功（response.code == 200?）
然后在判断业务系统的响应（errCode == custom_err_code?）

2024-12-24 03:33 UTC, SCMRCORE commented on community/function-calling/spring-ai-alibaba-starter-function-calling-baidutranslate/src/main/java/com/alibaba/cloud/ai/functioncalling/baidutranslate/BaidutranslateService.java
> +		if (jsonElement.getAsJsonObject().has("error_code")) {
Thank you for your guidance !

2024-12-24 04:38 UTC, PolarishT commented on community/function-calling/spring-ai-alibaba-starter-function-calling-baidutranslate/src/main/java/com/alibaba/cloud/ai/functioncalling/baidutranslate/BaidutranslateService.java
> +		Gson gson = new Gson();
那就全部使用Gson？

2024-12-25 03:35 UTC, SCMRCORE commented on community/function-calling/spring-ai-alibaba-starter-function-calling-baidutranslate/src/main/java/com/alibaba/cloud/ai/functioncalling/baidutranslate/BaidutranslateService.java
> +		Gson gson = new Gson();
Have changed the class to record and changed gson to jackson. Thanks for guiding

2024-12-25 05:32 UTC, PolarishT approved these changes
LGTM

2024-12-25 06:05 UTC, merged