add Express Delivery function calling
alibaba/spring-ai-alibaba pull request #323
Opened 2024-12-26 06:17 UTC by xiaohai-78

### Describe what this PR does / why we need it

### Does this pull request fix one issue?

### Describe how you did it

### Describe how to verify it

### Special notes for reviews

2024-12-26 11:47 UTC, PolarishT requested changes

2024-12-26 11:47 UTC, PolarishT commented on community/function-calling/spring-ai-alibaba-starter-function-calling-kuaidi100/pom.xml
> +	<dependencies>
add a new line

2024-12-26 11:47 UTC, PolarishT commented on community/function-calling/spring-ai-alibaba-starter-function-calling-kuaidi100/pom.xml
> +		</dependency>
remain a space

2024-12-26 11:47 UTC, PolarishT commented on community/function-calling/spring-ai-alibaba-starter-function-calling-kuaidi100/pom.xml
> +		<finalName>spring-ai-alibaba-starter-function-calling-kuaidi100</finalName>
这里最好是使用ExpressDelivery
spring-ai-alibaba-function-calling-expressdelivery

2024-12-26 11:47 UTC, PolarishT commented on spring-ai-alibaba-core/pom.xml
> +        <dependency>
测试用例的话 建议自己新建一个项目去进行debug，尽量不要core上去做

2024-12-26 11:48 UTC, PolarishT commented on community/function-calling/spring-ai-alibaba-starter-function-calling-kuaidi100/pom.xml
> +		<finalName>spring-ai-alibaba-starter-function-calling-kuaidi100</finalName>
这一块可以参考一下 function-calling/readme.md

2024-12-27 02:09 UTC, xiaohai-78 commented on community/function-calling/spring-ai-alibaba-starter-function-calling-kuaidi100/pom.xml
> +		<finalName>spring-ai-alibaba-starter-function-calling-kuaidi100</finalName>
用 spring-ai-alibaba-function-calling-expressdelivery 也行，但是我考虑之后如果有用户不想用 快递100，想用 菜鸟 或者其他快递平台的时候不好起名

2024-12-27 02:41 UTC, xiaohai-78 commented on community/function-calling/spring-ai-alibaba-starter-function-calling-kuaidi100/pom.xml
> +		<finalName>spring-ai-alibaba-starter-function-calling-kuaidi100</finalName>
要改吗

2024-12-27 09:41 UTC, PolarishT approved these changes
LGTM

2024-12-27 09:41 UTC, PolarishT commented on community/function-calling/spring-ai-alibaba-starter-function-calling-kuaidi100/pom.xml
> +		<finalName>spring-ai-alibaba-starter-function-calling-kuaidi100</finalName>
这样的话，那就不改了吧

2025-01-13 03:17 UTC, merged